version: "3"
services:
  nginx:
    build: ./requirements/nginx
    volumes:
      - wp-volume:/var/www/wordpress:ro
    ports:
      - 443:443
    env_file:
      - .env
    networks:
      - dhyeon-net
  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wp-volume:/var/www/wordpress
    expose:
      - 9000
    restart: always
    env_file:
      - .env
    networks: 
      - dhyeon-net
  mariadb: #db
    build: ./requirements/mariadb
    volumes:
      - db-volume:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - .env
    networks:
      - dhyeon-net
volumes:
  db-volume:
    # - /home/dhyeon/data/db
  wp-volume:
    # - /home/dhyeon/data/wp
networks:
  dhyeon-net: